### ISSUE TITLE
[Learn more | See more] should open a new StandardsHub page with specific content

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/sh-web#40]
When some one click in one of the buttons [Learn More | See More] we need to open a new StandardsHub page (new broser page) with:

 header (navigation, etc), footer (sitemap, etc) and the middle of the page is dedicated to that content, at the end it should be a navigation link to take you back to home page.

I believe that that is easy to compose with the content already created, so I just need one example and I can copy from there.

**Comment by pattiyaa** [comment]
Just to be sure about this requirement, normally the link in the website will lead the user to a specific URL (internal website URL or external link URL) in the same browser tab. 

If the user would like to open a new tab, they can process by "right click" and select "open link in new tab".
![image](https://user-images.githubusercontent.com/23195322/92385886-ecb77800-f13c-11ea-8392-fcdf39c6ed64.png)

I am not sure about your request, is it "to always open a new browser tab" for any button or link?
If this case, we are not recommended to do this because it's can make users confuse to open a new tab all the time. 

what do you think?

**Comment by jpradocueva** [comment]
Ok, I see your point. Personally I like the option to open a new tab but I understand what you mean.

So, let's follow your advice. A click in the button opens a new StandardsHub page on the same tab. So there is no confusion for the user.
Now, I have another question, for which I will open a new issue to don't get confused with the title of this issue. And it is about how to create a new page. 
See issue https://github.com/standardshub/sh-web/issues/47 
I will close this one.
